[package]
name = "tcp_terminal"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.43.0", features = ["full"] }
anyhow = "1.0.95"
clap = { version = "4.5.26", features = ["derive"] }
